apps/noticia/urls.py
from django.urls import path
from .views import NoticiaListview, CategoriaListview
from . import views

app_name = 'apps.noticia'

urlpatterns = [
    path("noticias", NoticiaListview.as_view(), name='noticias'),
    path("categorias", CategoriaListview.as_view(), name='categorias'),
    path('listarporcategoria/<str:categoria>',views.listarporcategoria, name='listarporcategoria'),
    path('AgregarNoticia/', views.AgregarNoticia.as_view(),name="AgregarNoticia"),
    path('AgregarCategoria/', views.AgregarCategoria.as_view(),name="AgregarCategoria"),
    path('BorrarCategoria/<pk>', views.BorrarCategoria.as_view(),name="BorrarCategoria"),
    path('Leerpost/<int:id>', views.LeerPost, name="Leerpost"),
    path('BorrarNoticia/<pk>', views.BorrarNoticia.as_view(),name="BorrarNoticia"),
    path('ActualizarNoticia/<pk>', views.ActualizarNoticia.as_view(), name="ActualizarNoticia"), 
]

sistema/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path("admin/", admin.site.urls, name='admin'),
    path('', principal, name='index'),
    path('', include('apps.noticia.urls')),
    path('', include('apps.usuario.urls')),
    path('', include('apps.comentario.urls')),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += staticfiles_urlpatterns() 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/noticia/models.py
from django.db import models
from django.utils import timezone

# Create your models here.


# --- Noticia
class Categoria(models.Model):
    nombre = models.CharField(max_length=50, null=False)

    def __str__(self):
        return self.nombre

class Noticia(models.Model):
    titulo = models.CharField(max_length=50, null=False)
    subtitulo = models.CharField(max_length=100, null=True, blank=True)
    fecha = models.DateTimeField(auto_now_add=True)
    texto = models.TextField(null=False)
    activo = models.BooleanField(default=True)
    categoria = models.ForeignKey(Categoria, on_delete=models.SET_NULL, null=True, default='Sin categoría')
    imagen = models.ImageField(null=True, blank=True, upload_to='noticia', default='noticia/default.png')
    publicado = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ('-publicado',)

    def __str__(self):
        return self.titulo

    def delete(self, using = None, keep_parents = False):
        self.imagen.delete(self.imagen.name)
        super().delete()

apps/noticia/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .models import Noticia
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Noticia, Categoria 
from apps.comentario.models import Comentarios
from apps.comentario.forms import ComentarioForm
from django.urls import reverse_lazy
from django.contrib import messages

# Create your views here.

class NoticiaListview(ListView):
    model = Noticia
    template_name = 'noticia/noticias.html'

class CategoriaListview(ListView):
    model = Categoria
    template_name = 'noticia/categorias.html'
    

class AgregarNoticia(LoginRequiredMixin, CreateView):
    model         = Noticia
    fields        = ['titulo', 'subtitulo','texto','categoria','imagen']
    template_name = 'noticia/AgregarNoticia.html'
    success_url   = reverse_lazy('apps.noticia:noticias')


class AgregarCategoria(LoginRequiredMixin,CreateView):
    model         = Categoria
    fields        = ['nombre', 'id']
    template_name = 'noticia/AgregarCategoria.html'
    success_url   = reverse_lazy('apps.noticia:AgregarNoticia')


class ActualizarNoticia(LoginRequiredMixin,UpdateView):
    model         = Noticia
    fields        = ['titulo', 'subtitulo','texto','categoria','imagen']
    template_name = 'noticia/AgregarNoticia.html'
    success_url   = reverse_lazy('apps.noticia:noticias')

class BorrarNoticia(LoginRequiredMixin,DeleteView):
	model 		  = Noticia
	template_name = 'noticia/borrarnoticia.html'
	success_url   = reverse_lazy('apps.noticia:noticias')

class BorrarCategoria(LoginRequiredMixin,DeleteView):
	model 		  = Categoria
	template_name = 'noticia/borrarcategoria.html'
	success_url   = reverse_lazy('apps.noticia:noticias')


def listarporcategoria(request, categoria):
    categoria2 = Categoria.objects.filter(nombre=categoria)
    noticia    = Noticia.objects.filter(categoria=categoria2[0].id)
    categorias  = Categoria.objects.all()
    context    = {
        'noticia' : noticia,
        'categoria': categorias,
    }
    return render(request,'noticia/listarporcategoria.html',context)


def ExistePost(id):
    for i in Noticia:
        if i.id == id:
            return i
    return None

def LeerPost(request, id):
	try:
		posts   = ExistePost(id)
	except Exception:
		posts   = Noticia.objects.get(id=id)
		comentarios = Comentarios.objects.filter(noticia=id)

	form = ComentarioForm(request.POST or None)
	if form.is_valid():
		if request.user.is_authenticated:
			aux         =  form.save(commit=False)
			aux.noticia = posts
			aux.usuario = request.user
			aux.save()
			form        = ComentarioForm()
		else:
			return redirect('usuario:login')
            
	context = {
		'titulo': 'noticia',
		'posts': posts,
		'form': form,
		'comentarios': comentarios,
	}
	return render(request,'noticia/post.html', context)

templates/noticia/ActualizarNoticia.html
{% extends 'base.html' %}


<section data-bs-version="5.1" class="menu cid-s48OLK6784" once="menu" id="menu1-h">


</section>


{% block contenido %}

<section data-bs-version="5.1" class="timeline3 cid-tf4QbpyVP7" id="timeline3-o">

{% if noticia %}
<div class="form-control">
    <div class="form-control">
        <h3 class="mbr-section-title mbr-fonts-style align-center mb-0 display-2"><strong>Noticias</strong></h3>
    </div>
    {% for n in Noticia_update %}
    <div class="timelines-container mt-4">
        <div class="row timeline-element first-separline mb-5">
           
            <p style='text-align: center;' class="mbr-timeline-date ">{{n.fecha}}</p>
            <div class="timeline-date col-12">
                <div class="timeline-date-wrapper">
                </div>
            </div>
            <div class="col-12 col-md-6">
                <div class="image-wrapper">
                    <img style="display: block;" class="d-block w-75" src="{{ n.imagen.url }}" title="">
                    <p class="btn btn-primary btn-sm item-categoria">{{n.categoria}}</p>
                </div>
            </div>
            <div class="col-12 col-md-6">
                <div class="timeline-text-wrapper">
                    <h4  style="text-align: center;" class="mbr-timeline-title mbr-fonts-style mb-0 display-5"><strong>{{n.titulo}}</strong></h4>
                    <h3 style="text-align: center;" style="display:contents;"><i>{{p.subtitulo}}</i></h3>
                    <p ><a href="{% url 'apps.noticia:LeerPost' n.id %}" class="btn btn-primary" style="margin-left: 30%; font-size: small;">Leer Más</a></p>
                </div>
            </div>
        </div>
    </div>{% endfor %}
</div>
</section>
{% endif %}
{% comment %} <style>
button {
    display: inline-block;
    color: #252537;
    outline: none;
    border: none;
    text-align: center;
    transition: all 0.2s linear;
    margin: 7% auto;
    letter-spacing: 0.05em;
}
/* buttons hover */
button:hover {
    transform: translatey(3px);
    box-shadow: none;
}

/* buttons hover Animation */
button:hover {
    animation: ani9 0.4s ease-in-out infinite alternate;
}

@keyframes ani9 {
    0% {
        transform: translateY(3px);
    }

    100% {
        transform: translateY(5px);
    }
}
</style> {% endcomment %}

{% endblock  %}

templates/noticia/AgregarCategoria.html
{% extends 'base.html' %}
{% load static %}
{% block contenido %}

<div class="main-container" style="text-align: center; margin-top: 12%;">
    <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
                

                        
                           <h2>Agregar categoria</h2>
                           <p>Ingrese los datos y presione el botón de guardar</p>
                        
                        {{form.as_p}}
                        
                        <input class="btn btn-primary" type="submit" value="Agregar">
               
    </form>
</div>
                {% comment %} <style>
                    @import url('https://fonts.googleapis.com/css?family=Abel|Abril+Fatface|Alegreya|Arima+Madurai|Dancing+Script|Dosis|Merriweather|Oleo+Script|Overlock|PT+Serif|Pacifico|Playball|Playfair+Display|Share|Unica+One|Vibur');
            /* End Fonts */
            /* Start Global rules */
            * {
                padding: 0;
                margin: 0;
                box-sizing: border-box;
            }
           
            form {
                width: 500px;
                min-height: 500px;
                height: auto;
                border-radius: 5px;
                margin: 2% auto;
                box-shadow: 0 9px 50px hsla(20, 67%, 75%, 0.31);
                padding: 2%;
                /*background-image: linear-gradient(-225deg, #E3FDF5 50%, #FFE6FA 50%);*/
            }
            /* form Container */
            form .con {
                display: -webkit-flex;
                display: flex;
              
                -webkit-justify-content: space-around;
                justify-content: space-around;
              
                -webkit-flex-wrap: wrap;
                flex-wrap: wrap;
              
                  margin: 0 auto;
            }
            header {
                margin: 2% auto 10% auto;
                text-align: center;
            }
            .input-item {
                background: #fff;
                color: #333;
                padding: 14.5px 0px 15px 9px;
                border-radius: 5px 0px 0px 5px;
            }
            /* inputs form  */
            input[class="form-input"]{
                width: 240px;
                height: 50px;
              
                margin-top: 2%;
                padding: 15px;
                
                font-size: 16px;
                font-family: 'Abel', sans-serif;
                color: #5E6472;
              
                outline: none;
                border: none;
              
                border-radius: 0px 5px 5px 0px;
                transition: 0.2s linear;
                
            }
            input[id="txt-input"] {width: 250px;}
            /* focus  */
            input:focus {
                transform: translateX(-2px);
                border-radius: 5px;
            }
            
            /* //////////////////////////////////////////// */
            /* //////////////////////////////////////////// */
            
            /* input[type="text"] {min-width: 250px;} */
            /* buttons  */
            button {
                display: inline-block;
                color: #252537;
              
                width: 280px;
                height: 50px;
              
                padding: 0 20px;
                background: #fff;
                border-radius: 5px;
                
                outline: none;
                border: none;
              
                cursor: pointer;
                text-align: center;
                transition: all 0.2s linear;
                
                margin: 7% auto;
                letter-spacing: 0.05em;
            }
            /* Submits */
            .submits {
                width: 48%;
                display: inline-block;
                float: none;
                margin-left: 2%;
            }
            /* buttons hover */
            button:hover {
                transform: translatey(3px);
                box-shadow: none;
            }
            
            /* buttons hover Animation */
            button:hover {
                animation: ani9 0.4s ease-in-out infinite alternate;
            }
            @keyframes ani9 {
                0% {
                    transform: translateY(3px);
                }
                100% {
                    transform: translateY(5px);
                }
            }
                </style> {% endcomment %}
                


{% endblock  %}

templates/noticia/AgregarNoticia.html
{% extends 'base.html' %}
{% load static %}
{% block contenido %}

<div class="portfolio-info" style="text-align: center; margin-top: 12%;">
    <form action="" method="POST" enctype="multipart/form-data">
        <form method="post">{% csrf_token %}
            <div class="overlay">
                <form>
                    <div class="con">
                        <header class="portfolio-info">
                            <h2>Agregar noticia</h2>
                            <p>Ingrese los datos y presione el botón de guardar, luego podrá ver su notica en la sección
                                noticias:</p>
                        </header>
                        <div>
                            {{form.as_p}}
                            {{form.media}}

                            <input class="btn btn-outline-secondary" type="submit" data-bs-toggle="modal"
                                style="text-align: center;" data-bs-target="#exampleModal" value="Guardar noticia" />
                            <!-- Modal -->
                                <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                                    aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">Noticia cargada</h5>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                    aria-label="Close"></button>
                                            
                                                <div class="modal-body" data-aos='transition-delay: .3s;'>
                                                    Su noticia fue cargada con éxito
                                                </div>
                                                <div class="modal-footer">
                                                    <a class="btn btn-outline-secondary" href="{% url 'index' %}">Volver al
                                                        inicio</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                        </div>
                    </div>
                </form>
            </div>
        </form>
    </form>
</div>
<style>
    {% comment %} @import url('https://fonts.googleapis.com/css?family=Abel|Abril+Fatface|Alegreya|Arima+Madurai|Dancing+Script|Dosis|Merriweather|Oleo+Script|Overlock|PT+Serif|Pacifico|Playball|Playfair+Display|Share|Unica+One|Vibur');

    /* End Fonts */
    /* Start Global rules */
    * {
        padding: 0;
        margin: 0;
        box-sizing: border-box;
    }

    form {
        width: 1000px;
        min-height: 500px;
        height: auto;
        border-radius: 5px;
        margin: 2% auto;
        box-shadow: 0 9px 50px hsla(20, 67%, 75%, 0.31);
        padding: 2%;
        /*background-image: linear-gradient(-225deg, #249ca9 50%, #249ca9 50%);*/
    }

    /* form Container */
    form .con {
        display: -webkit-flex;
        display: flex;

        -webkit-justify-content: space-around;
        justify-content: space-around;

        -webkit-flex-wrap: wrap;
        flex-wrap: wrap;

        margin: 0 auto;
    }

    header {
        margin: 2% auto 10% auto;
        text-align: center;
    }

    .input-item {
        background: #fff;
        color: #333;
        padding: 14.5px 0px 15px 9px;
        border-radius: 5px 0px 0px 5px;
    }

    /* inputs form  */
    input[class="form-input"] {
        width: 240px;
        height: 50px;

        margin-top: 2%;
        padding: 15px;

        font-size: 16px;
        font-family: 'Abel', sans-serif;
        color: #5E6472;

        outline: none;
        border: none;

        border-radius: 0px 5px 5px 0px;
        transition: 0.2s linear;

    }

    input[id="txt-input"] {
        width: 250px;
    }

    /* focus  */
    input:focus {
        transform: translateX(-2px);
        border-radius: 5px;
    }

    /* //////////////////////////////////////////// */
    /* //////////////////////////////////////////// */

    /* input[type="text"] {min-width: 250px;} */
    /* buttons  */
    button {
        display: inline-block;
        color: #252537;

        width: 280px;
        height: 50px;

        padding: 0 20px;
        background: #fff;
        border-radius: 5px;

        outline: none;
        border: none;

        cursor: pointer;
        text-align: center;
        transition: all 0.2s linear;

        margin: 7% auto;
        letter-spacing: 0.05em;
    }

    /* Submits */
    .submits {
        width: 48%;
        display: inline-block;
        float: none;
        margin-left: 2%;
    }

    /* buttons hover */
    button:hover {
        transform: translatey(3px);
        box-shadow: none;
    }

    /* buttons hover Animation */
    button:hover {
        animation: ani9 0.4s ease-in-out infinite alternate;
    }

    @keyframes ani9 {
        0% {
            transform: translateY(3px);
        }

        100% {
            transform: translateY(5px);
        }
    }
</style> {% endcomment %}


{% endblock  %}

templates/noticia/borrarcategoria.html
{% extends 'base.html' %}

{% block contenido %}

<form method="post" >
    {%csrf_token%}
    <div class='main-container' style="text-align: center; margin-top: 12%; margin-bottom: 12%;">
        <h3>¿Está seguro que desea eliminar la categoría {{categorias.titulo}} ?</h3>
        <input class="btn btn-danger" type="submit" value='Si, eliminar'></input>
        <a class="btn btn-success" href="{% url 'apps.noticia:categorias' %}">Cancelar</a>
    </div>
</form>
{% endblock %}

templates/noticia/borrarnoticia.html
{% extends 'base.html' %}

{% block contenido %}

<form method="post" >
    {%csrf_token%}
    <div class='main-container' style="text-align: center; margin-top: 12%; margin-bottom: 12%;">
        <h3>Esta seguro que desea eliminar la noticia {{noticia.titulo}} ?</h3>
        <input class="btn btn-danger" type="submit" value='Si, eliminar'></input>
        <a class="btn btn-success" href="{% url 'apps.noticia:noticias' %}">Cancelar</a>
    </div>
</form>
{% endblock %}

templates/noticia/categorias.html
{% extends 'base.html' %}
{% block contenido %}

<section class="services section-bg">
    
        <div class="section-title" data-aos="fade-down">
            <h2><br>Categorías</h2>
            <p>Bienvenido <strong>{{user.username}}</strong>. Elija la categoria por la que quiere filtrar. </p>
        </div>
    
</section>

<section id="services" class="services section-bg" style="padding: 0px;">
    {% if not categoria_list %}
        <div class="alert alert-info">No existen categorías</div>
        {% else %}
            <div class="container" data-aos="fade-up" >
                <div class="row" style="text-align:center">
                    {% for i in categoria_list %}
                            <div class="col-xl-3 col-md-8 align-items-stretch" data-aos="zoom-in" data-aos-delay="50" style="padding: 10px 10px;">
                                  <div class="icon-box">
                                    <div class="icon"><i class="bx bxl-dribbble" style="align:center;"></i></div>
                                    <h4><a href="{% url 'apps.noticia:listarporcategoria' i.nombre %}">{{i.nombre}}</a></h4>
                                  </div>
                            </div>

                    {% endfor %}
                </div>
            </div>
        {% endif %}
</section>

{% endblock contenido %}

templates/noticia/listarporcategoria.html
{% extends 'base.html' %}



        {%for i in categoria %}

        <li ><a  class="dropdown-item" href="{% url 'apps.noticia:listarporcategoria' i.id %}">{{i.id}}</a></li>
        <li ><a  class="dropdown-item" href="{% url 'apps.noticia:listarporcategoria' i.nombre %}">{{i.nombre}}</a></li>

        {% endfor %}

{% block contenido %}


<section data-bs-version="5.1" class="timeline3 cid-tf4QbpyVP7" id="timeline3-o">
    
    
    <div class="container-fluid">
           
            <div class="section-title" data-aos="fade-down">
                <h4><strong><br>{{nombre}}</strong></h4>
            </div>
            
            {% for p in noticia %}
            <div class="timelines-container mt-4" data-aos="fade-up">
                <div class="row timeline-element first-separline mb-5">
                    <p style='text-align: center;' class="mbr-timeline-title mbr-fonts-style mb-0 display-5">{{p.titulo}}</p>
                    <div class="timeline-date col-12">
                        <div class="timeline-date-wrapper">
                        </div>
                    </div>
                    <div class="col-12 col-md-6">
                        <div class="image-wrapper">
                            <img class="d-block w-75" src="{{ p.imagen.url }}" title="">

                            <p class="btn btn-primary btn-sm item-categoria">{{p.categoria}}</p>
                        </div>
                    </div>
                    <div class="col-12 col-md-6">
                        <div class="timeline-text-wrapper">
                            <h4 class="mbr-timeline-date display-7">{{p.fecha}}</h6>
                            <h3 style="text-align: center;" style="display:contents;">{{p.subtitulo}}</h3>
                            <p class="mbr-text mbr-fonts-style mt-3 mb-0 display-7">
                                <a href="{% url 'apps.noticia:Leerpost' p.id %}" class="btn btn-primary" style="margin-left: 30%;">Leer Más</a></p>
                        </div>
                    </div>
                </div>
            </div>{% endfor %}
        
    </div>
</section>
{% endblock %}

templates/noticia/noticias.html
{% extends 'base.html' %}

<title>{% block title %} Noticias {% endblock title %}</title>

{% block contenido %}

   
    <section id="breadcrumbs" class="breadcrumbs">
      <div class="container">

        <ol>
          <h2 style="text-align-center">Noticias</h2>
        </ol>
        <h5>Mirá nuestras actividades</h5>

      </div>
    </section>


    {% for n in noticia_list %}
    <section id="portfolio-details" class="portfolio-details" data-aos="zoom-in">
      <div class="container">
        
          <div class="row gy-4">
           
            <div class="col-lg-8">
              <div class="portfolio-details-slider swiper">
                <div class="swiper-wrapper">
                  
                  <div class="swiper-slid">
                    <img class="img-fluid" src="{{n.imagen.url}}" alt="">
                  </div>

                  {% comment %} <div class="swiper-slide">
                    <img src="assets/img/portfolio/portfolio-2.jpg" alt="">
                  </div> {% endcomment %}

                  {% comment %} <div class="swiper-slide">
                    <img src="assets/img/portfolio/portfolio-3.jpg" alt=""> 
                  </div>  {% endcomment %}

                </div>
                <div class="swiper-pagination"></div>
              </div>
            </div>



            <div class="col-lg-4">
              <div class="portfolio-info" >
                <h3 style="text-align: center;">{{n.titulo}}</h3>
                <ul>
                  <li><strong>Categoria</strong>: {{n.categoria}}</li>
                  <li><strong>Publicado el</strong>: {{n.publicado}}</li>
                  <li><strong>Dejar tu comentario</strong>: <a href="{% url 'apps.noticia:Leerpost' n.id %}"><strong>
                  Aquí</strong></a></li>
                </ul>
              </div>
              <div class="portfolio-description" style="text-align: center;">
                <h5>{{n.subtitulo}}</h5>
                <p>{{n.texto}}</p>
              </div>
            </div>
           
          </div>
        
      </div>
    </section>
    {% endfor %}

{% endblock  %}

templates/noticia/noticias2.html
{% extends 'base.html' %}
{% load static %}
<title>{% block title %} Noticias {% endblock title %}</title>

{% block contenido %}

<section id="services" class="services section-bg">
  <div class="container" data-aos="fade-up">

    <div class="section-title">
      <h2>Noticias</h2>
      <p>Mirá nuestras actividades</p>
    </div>

    <div class="row">

        {% for n in object_list %}

                <div class="container" data-aos="zoom-in">
                  
                  <div class="row">
                    <div class="col-lg text-center text-lg">

                        <div class="icon-box">
      
                          <h4><a><br>{{n.titulo}}</a></h4>
                          <img src="{{n.imagen.url}}" class = "img-fluid animated" alt = "">
                          {% comment %} <ul class="dropdown-menu" aria-labelledby="navbarDropdown" >
                            {%for i in categoria %}
                            <li ><a  class="dropdown-item" href="{% url 'apps.noticia:listarPorCategoria' i.nombre %}">{{i.nombre}}</a></li>
                            {% endfor %}
                          </ul> {% endcomment %}
                          
                          <h5><a href=""><br>{{n.subtitulo}}</a></h5>
                          <h6><a href="">{{n.publicado}}</a></h6>
                          <p>{{n.texto}}</p>
                          <a class="cta-btn align-middle" href="{% url 'apps.noticia:Leerpost' n.id %}"><br>Podés comentar esta noticia aquí</a>
                        </div>

                        <section id="portfolio" class="portfolio">
                          <div class="container" data-aos="fade-up">
                          </div>
                        </section>
                    </div>
                  </div>
                </div>
              
        {% endfor %}
         
        

    </div>

  </div>
</section>

{% endblock  %}

templates/noticia/post.html
{% extends 'base.html' %}
{% block title %}Comentar esta noticia{%endblock %}

{% block contenido %}

{% if user.is_superuser %}

<section class="d-flex align-items-center">
    <div class="container" style= "padding-top:40px;">
        <div class="row">
            <div class="col-lg-12 d-flex flex-column">
                

                    <button class="btn-get-started scrollto" type="button" data-bs-toggle="dropdown" style="padding: 3px 20px; border-radius: 50px; border: 2px solid #47b2e4; background-color: #fff">Administrar noticia</button>
                    <ul class="dropdown-menu"  aria-labelledby="dropdownMenuButton1">
                        <li><a  class="dropdown-item"  href="{% url 'apps.noticia:ActualizarNoticia' posts.pk %}">Modificar </a></li>
                        <li><a  class="dropdown-item"  href="{% url 'apps.noticia:BorrarNoticia' posts.pk %}">Eliminar </a></li>
                    </ul>

                
            </div>
        </div>
    </div>
</section>
{% endif %}


<section class="services section-bg">
            <div class="container" data-aos="fade-up">
                <div class="section-title">
                    <h2 class="section-title"><strong>{{posts.titulo | capfirst}}</strong></h2>
                    <img class="img-fluid" src="{{ posts.imagen.url }}">
                    <p class="portfolio-details">Categoría: {{posts.categoria | capfirst}} // Fecha de publicación: {{posts.fecha}}</p> 
                </div>

           
                <div class="section-title">
                    <h4 class="section-title" style="padding-top:60px;">{{posts.subtitulo | capfirst}}</h4>
                    <p class="col-lg text-center text-lg">{{posts.texto | capfirst}}</p>
                </div>
            </div>
</section>


<section id="contact" class="contact">
    <div class="container" data-aos="fade-up">
        <div class="section-title">
            <h2>Dejanos tu comentario</h2>
            <p>Comentarios: {{comentarios.count}}</p>
                {% include 'comentario/listadoComentario.html' %}
        </div>
        <div class="section-title">
                {% include 'comentario/agregarComentario.html' %}
        </div>
    </div>
</section>

{%endblock %}